; PlatformIO Project Configuration File

[platformio]
description = "ESP32 - Process-Manager Bubi"
default_envs = az-delivery-devkit-v4

[env:az-delivery-devkit-v4]
platform = espressif32
board = az-delivery-devkit-v4
framework = arduino
upload_port = /dev/ttyUSB*
monitor_speed = 115200
lib_deps = 
	iakop/LiquidCrystal_I2C_ESP32@^1.1.6

